import prisma from "@/lib/prisma";
import { Brag } from "@/types";
import { GetServerSideProps } from "next";
import Head from "next/head";

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  const brag = await prisma.brag.findUnique({
    where: {
      id: String(params?.id),
    },
  });

  return {
    props: {
      brag,
    },
  };
};

type BragItemProps = {
  params: {
    id: string;
  };
  brag: Brag;
};

export default function BragItem(props: BragItemProps) {
  return (
    <>
      <Head>
        <title>Brag Item</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{props.brag?.title}</h1>
    </>
  );
}
