import Head from "next/head";
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import { Button } from "@mantine/core";
import { useRouter } from "next/router";

export default function SignOut() {
  const supabase = useSupabaseClient();
  const router = useRouter();

  async function handleSignOut() {
    await supabase.auth.signOut();
    router.push("/");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container" style={{ padding: "50px 0 100px 0" }}>
        <Button onClick={handleSignOut}>Sign out</Button>
      </div>
    </>
  );
}
