import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hasBrags = api.bragsheets.hasBrags.useQuery();
  const { mutate } = api.bragsheets.create.useMutation();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-center bg-gradient-to-r from-green-400 via-blue-500 to-purple-600 py-12 sm:px-6 lg:px-8">
        <div className="sm:mx-auto sm:w-full sm:max-w-md">
          <h2 className="mt-6 text-center text-4xl font-extrabold text-white">
            Welcome to BragSheet
          </h2>
          <p className="mt-2 text-center text-lg text-white">
            Easily create and manage your bragsheet
          </p>
        </div>
        <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
          <div className="rounded-xl bg-white p-8 shadow-2xl">
            <div className="space-y-6">
              <div className="flex items-center space-x-4">
                <div className="rounded-lg bg-yellow-400 p-4">
                  <i className="fas fa-trophy text-2xl text-white"></i>
                </div>
                <div>
                  <h3 className="text-lg font-medium leading-6 text-gray-900">
                    Keep Track of Your Achievements
                  </h3>
                  <p className="mt-2 text-sm text-gray-500">
                    Record your accomplishments, skills, and experiences to
                    showcase your strengths and stand out from the competition.
                  </p>
                </div>
              </div>
              <div className="flex items-center space-x-4">
                <div className="rounded-lg bg-pink-500 p-4">
                  <i className="fas fa-sync-alt text-2xl text-white"></i>
                </div>
                <div>
                  <h3 className="text-lg font-medium leading-6 text-gray-900">
                    Seamless Integration
                  </h3>
                  <p className="mt-2 text-sm text-gray-500">
                    Integrate with popular services like Slack and Raycast to
                    easily add brags and manage your bragsheet.
                  </p>
                </div>
              </div>
              <div className="flex items-center space-x-4">
                <div className="rounded-lg bg-purple-600 p-4">
                  <i className="fas fa-paint-brush text-2xl text-white"></i>
                </div>
                <div>
                  <h3 className="text-lg font-medium leading-6 text-gray-900">
                    Customizable & Exportable
                  </h3>
                  <p className="mt-2 text-sm text-gray-500">
                    Personalize your bragsheet with various styles and layouts,
                    and export it in multiple formats to share with others.
                  </p>
                </div>
              </div>
            </div>
            <div className="mt-6">
              <a
                href="auth/signup"
                className="flex w-full justify-center rounded-md border border-transparent bg-gradient-to-r from-yellow-400 to-pink-500 py-3 px-4 text-lg font-bold text-white shadow-sm hover:from-yellow-300 hover:to-pink-400"
              >
                Get Started
              </a>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {/* {sessionData && <span>Logged in as {sessionData.user?.name}</span>} */}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
